---
ID: "54d4f3d5-e293-4c54-9ada-c2dfc21279a1"
Parent: "1cc41a46-5ab8-4487-b321-fa4b8847eb37"
Template: "242d7c0e-8e59-4295-a8cc-01e04a8a7ba0"
Path: /sitecore/content/Headless/Astro/Settings
BranchID: "45cf9f42-b3ac-4412-aab9-f8441c7e448e"
SharedFields:
- ID: "0129da3f-8c86-4591-ae32-6ec923413923"
  Hint: DictionaryDomain
  Value: "{E391D69D-C3D0-41E4-B83E-411F04ACBC6B}"
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{C2DC4690-AF44-48C7-BB21-90D1AD246732}"
- ID: "1864e99d-c29a-40bf-96e0-b3e7896a013b"
  Hint: UseLanguageSpecificLayout
  Value: 
- ID: "300fb7a0-b27f-44dd-9af0-b37a19723e0e"
  Hint: RouteTemplateName
  Value: Settings Route
- ID: "32ce6bbe-4217-46e5-9335-42793884cbe3"
  Hint: AppTemplate
  Value: "{1EC2366D-519D-496C-B3E9-89E558CF2BD5}"
- ID: "3e4f559f-8e59-4405-b50d-619811371f6c"
  Hint: Name
  Value: astro
- ID: "5764d2d4-724d-4313-a81b-9246c911faff"
  Hint: AppDatasourcesPath
  Value: "{72D88DE0-B6DE-4C3D-8A84-7C85B6677F3F}"
- ID: "5ca117eb-8782-4a4f-9f2f-30de31fc2e34"
  Hint: PlaceholdersPath
  Value: "{FEE78395-7D1A-4761-AF55-43F7309D6BAD}"
- ID: "5e8ed724-126a-4bb7-8106-85c2d1042c9e"
  Hint: ServerSideRenderingEngineApplicationUrl
  Value: "http://host.docker.internal:4321/"
- ID: "72e83c8d-3578-4e50-b4c0-93a78a1729f2"
  Hint: FilesystemPath
  Value: /dist/Astro
- ID: "797d2f63-d5c4-4c4c-b21f-d3e250e2ab12"
  Hint: DeploymentSecret
  Value: g0ohvcr6th9re6jadhsuekf0nn2aa5fhhsgodh5fxk0n
- ID: "89849738-34ee-46bc-b525-825f1153189e"
  Hint: ServerSideRenderingEngineEndpointUrl
  Value: "http://host.docker.internal:4321/api/editing/render"
- ID: "9016141c-ff51-40f2-9135-40f5161b9784"
  Hint: ServerSideRenderingEngine
  Value: http
- ID: "a7bbad73-b933-49ff-95c8-1c269cb35e7c"
  Hint: DictionaryPath
  Value: "{E391D69D-C3D0-41E4-B83E-411F04ACBC6B}"
- ID: "af332c24-fe17-41e7-8caf-8e64c588fe72"
  Hint: EditingTheme
  Value: "{3BCAB9EF-1E4F-4C23-B452-783BB82AA686}"
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 2000
- ID: "c8d002f9-9518-4c5e-9baa-6617e13f0797"
  Hint: LayoutPath
  Value: "{AAFFF035-F506-4549-8E0A-D933F2E256C8}"
- ID: "e8881464-38af-4655-be4a-ee10586578a2"
  Hint: Templates
  Value: "{28F4B3EA-94E8-4E10-BD78-88D6F2811EB1}"
- ID: "f29428d5-1285-48b8-a884-44057965829a"
  Hint: RenderingsPath
  Value: "{7B1BB05F-312E-444B-BC2A-D63AC7AB9B73}"
- ID: "f6d8a61c-2f84-4401-bd24-52d2068172bc"
  Hint: __Originator
  Value: "{0FEEB907-58F0-44DE-B08C-2F43C063D0A5}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230412T130125Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "6170b36e-7a09-4edd-ab8c-80c02f6471ef"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230506T151318Z
