---
ID: "242d7c0e-8e59-4295-a8cc-01e04a8a7ba0"
Parent: "28f4b3ea-94e8-4e10-bd78-88d6f2811eb1"
Template: "ab86861a-6030-46c5-b394-e8f99e8b87db"
Path: /sitecore/templates/Project/Headless/JSS Settings
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: Office/32x32/gearwheels.png
- ID: "12c33f3f-86c5-43a5-aeb4-5598cec45116"
  Hint: __Base template
  Value: |
    {EC848505-D30C-4BDC-A0AA-7CC9D320085E}
    {6175F4C7-F87F-4F7F-928E-4C5CA5DFFAF4}
    {CBC14160-BED0-4AA2-9387-4C13179205B9}
    {A7228B46-610D-4A17-9F61-649F3A30AAAE}
    {59F55DFC-4DB7-422F-9D40-F2ECF66C8499}
- ID: "f7d48a55-2158-4f02-9356-756654404f73"
  Hint: __Standard values
  Value: "{C242FAE2-A1C1-4715-812E-5F1DB179C7A0}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230412T130059Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "7a6c4689-42e9-4222-b56a-30fc04a5c594"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230412T130100Z
