---
ID: "44359ae4-02ba-41ff-923d-a6543c99964f"
Parent: "ba8b9b4c-4d49-4563-b5d2-0135954b988a"
Template: "ba8b9b4c-4d49-4563-b5d2-0135954b988a"
Path: "/sitecore/templates/Project/Headless/Astro/Integrations/Styleguide-ReactUsage/__Standard Values"
SharedFields:
- ID: "ca9b9f52-4fb0-4f87-a79f-24dea62cda65"
  Hint: __Default workflow
  Value: "{6C59AE29-D0A1-4B77-9305-0ABAB21D5FE5}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230414T124648Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\JssImport
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "b8d3a0c1-b498-4cdb-85cf-83900b6ac003"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230606T140356Z
